[package]
edition = "2021"
name = "rust-srtp-bench"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srtp = "0.7.0"
hex="0.4.3"